swagger: "2.0"
info:
  version: "1.0.0"
  title: Swagger DotaEz
  contact:
    name: Everton Galdino da Silva
basePath: /api
schemes:
  - http
  - https
paths:
  /hero:
    post:
      tags:
        - hero
      summary: Add a new hero
      description: ""
      operationId: addHero
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: Hero
          description: Hero object that needs to be added to the store
          required: true
          schema:
            $ref: "#/definitions/Hero"
      responses:
        "405":
          description: Invalid input
    put:
      tags:
        - hero
      summary: Update an existing hero
      description: ""
      operationId: updateHero
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: Hero object that needs to be added to the store
          required: false
          schema:
            $ref: "#/definitions/Hero"
      responses:
        "405":
          description: Validation exception
        "404":
          description: Hero not found
        "400":
          description: Invalid ID supplied
  /hero/findByName:
    get:
      tags:
        - hero
      summary: Find Hero by Name
      description: ""
      operationId: findHeroByName
      produces:
        - application/json
        - application/xml
      parameters:
        - in: query
          name: status
          description: Names values that need to be considered for filter
          required: false
          type: string
      responses:
        "200":
          description: successful operation
          schema:
            type: string
            items:
              $ref: "#/definitions/Hero"
        "400":
          description: Invalid name value
  /hero/findByTypeHero:
    get:
      tags:
        - hero
      summary: Find hero by types
      description: ""
      operationId: findHeroByTypeHero
      produces:
        - application/json
        - application/xml
      parameters:
        - in: query
          name: tags
          description: Tags to filter by
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
      responses:
        "200":
          description: successful operation
          schema:
            type: array
            items:
             $ref: "#/definitions/Hero"
        "400":
          description: Invalid tag value
  /hero/{heroId}:
    get:
      tags:
        - hero
      summary: Find hero by ID
      description: ""
      operationId: getHeroById
      produces:
        - application/json
        - application/xml
      parameters:
        - in: path
          name: heroId
          description: ID of hero that needs to be fetched
          required: true
          type: integer
          format: int64
      responses:
        "404":
          description: Hero not found
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Hero"
        "400":
          description: Invalid ID supplied
    post:
      tags:
        - hero
      summary: Updates a hero in the store with form data
      description: ""
      operationId: updateHeroWithForm
      produces:
        - application/json
        - application/xml
      parameters:
        - in: path
          name: heroId
          description: ID of hero that needs to be updated
          required: true
          type: string
        - in: formData
          name: name
          description: Updated name of the hero
          required: true
          type: string
        - in: formData
          name: typeHero
          description: Updated TypeHero of the hero
          required: true
          type: string
        - in: formData
          name: status
          description: Updated Status of the hero
          required: true
          type: string
        - in: formData
          name: skill
          description: Updated Skill of the hero
          required: true
          type: string
        - in: formData
          name: build
          description: Updated Build of the hero
          required: true
          type: string
      responses:
        "405":
          description: Invalid input
    delete:
      tags:
        - hero
      summary: Deletes a hero
      description: ""
      operationId: deleteHero
      produces:
        - application/json
        - application/xml
      parameters:
        - in: header
          name: heroId
          description: ""
          required: true
          type: string
        - in: path
          name: heroId
          description: Hero id to delete
          required: true
          type: integer
          format: int64
      responses:
        "400":
          description: Invalid Hero value
  /user:
    post:
      tags:
        - user
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: Created user object
          required: false
          schema:
            $ref: "#/definitions/User"
      responses:
        default:
          description: successful operation
  /users/login:
    get:
      tags:
        - user
      summary: Logs user into the system
      description: ""
      operationId: loginUser
      produces:
        - application/json
        - application/xml
      parameters:
        - in: query
          name: username
          description: The user name for login
          required: false
          type: string
        - in: query
          name: password
          description: The password for login in clear text
          required: false
          type: string
      responses:
        "200":
          description: successful operation
          schema:
            type: string
        "400":
          description: Invalid username/password supplied
  /users/logout:
    get:
      tags:
        - user
      summary: Logs out current logged in user session
      description: ""
      operationId: logoutUser
      produces:
        - application/json
        - application/xml
      responses:
        default:
          description: successful operation
  /users/{username}:
    get:
      tags:
        - user
      summary: Get user by user name
      description: ""
      operationId: getUserByName
      produces:
        - application/json
        - application/xml
      parameters:
        - in: path
          name: username
          description: The name that needs to be fetched. Use user1 for testing.
          required: true
          type: string
      responses:
        "404":
          description: User not found
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/User"
        "400":
          description: Invalid username supplied
    put:
      tags:
        - user
      summary: Updated user
      description: This can only be done by the logged in user.
      operationId: updateUser
      produces:
        - application/json
        - application/xml
      parameters:
        - in: path
          name: username
          description: name that need to be deleted
          required: true
          type: string
        - in: body
          name: body
          description: Updated user object
          required: false
          schema:
            $ref: "#/definitions/User"
      responses:
        "404":
          description: User not found
        "400":
          description: Invalid user supplied
    delete:
      tags:
        - user
      summary: Delete user
      description: This can only be done by the logged in user.
      operationId: deleteUser
      produces:
        - application/json
        - application/xml
      parameters:
        - in: path
          name: username
          description: The name that needs to be deleted
          required: true
          type: string
      responses:
        "404":
          description: User not found
        "400":
          description: Invalid username supplied
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      Login:
        type: string
      email:
        type: string
      password:
        type: string
      nickNameDOTA:
        type: string
      userStatus:
        type: integer
        format: int32
        description: User Status
  Skill:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      effect:
        type: string
      dano:
        type: integer
      typeDano:
        type: string
      hero:
        $ref: "#/definitions/Hero"
        
  Hero:
    type: object
    properties:
      id:
        type: integer
      skill:
        $ref: "#/definitions/Skill"
      name:
        type: string
      typeHero:
        $ref: "#/definitions/TypeHero"
      status:
        $ref: "#/definitions/Status"
      build:
        $ref: "#/definitions/Build"
        
  TypeHero:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  Build:
    type: object
    properties:
      id:
        type: integer
        format: int64
      hero:
        $ref: "#/definitions/Hero"
      item:
        $ref: "#/definitions/Item"
      author:
        type: string
  Item:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      effect:
        type: string
      Dano:
        type: integer
        format: int64
      typeItem:
        type: string
  Status:
    type: object
    properties:
      strenght:
        type: string
      agility:
        type: string
      intellect:
        type: string

        